apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: hpa-sample
spec:
  limits:
    - max:
        cpu: "800m"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "99Mi"
      # default limit
      default:
        cpu: "800m"
        memory: "900Mi"
      defaultRequest:
        cpu: "110m"
        memory: "111Mi"
      type: Container